insert into books (author, title, priceOld, price) values ('Drucie Goodbourn', 'Exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author, title, priceOld, price) values ('Marcia Aggiss', 'Utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author, title, priceOld, price) values ('Giovanni Bigg', 'Extend strategic e-services', '$272.00', '$151.04');
insert into books (author, title, priceOld, price) values ('Duffie Eynon', 'Iterate integrated solutions', '$271.58', '$141.40');
insert into books (author, title, priceOld, price) values ('Anselma McKennan', 'Cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author, title, priceOld, price) values ('Gert Kira', 'Architect vertical ROI', '$282.54', '$102.61');
insert into books (author, title, priceOld, price) values ('Clerc Djakovic', 'Disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author, title, priceOld, price) values ('Stacee Elsy', 'Extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author, title, priceOld, price) values ('Dorotea Bonhill', 'Integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author, title, priceOld, price) values ('Minni Bunney', 'Revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author, title, priceOld, price) values ('Berty Gandley', 'Enhance innovative e-services', '$256.54', '$160.98');
insert into books (author, title, priceOld, price) values ('Raynard Tesdale', 'Maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author, title, priceOld, price) values ('Joanna Hutfield', 'Scale integrated architectures', '$257.66', '$32.97');
insert into books (author, title, priceOld, price) values ('Dannie Glidder', 'E-enable frictionless web services', '$288.19', '$90.52');
insert into books (author, title, priceOld, price) values ('Timmie Adshede', 'Strategize B2B channels', '$232.27', '$44.83');
insert into books (author, title, priceOld, price) values ('Fernando Neads', 'Syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author, title, priceOld, price) values ('Teddy Guilliland', 'Utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author, title, priceOld, price) values ('Paloma Grebert', 'Cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author, title, priceOld, price) values ('Kristos Usher', 'Embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author, title, priceOld, price) values ('Darcey Rohmer', 'Target innovative paradigms', '$298.94', '$130.01');
insert into books (author, title, priceOld, price) values ('Cristie Isacsson', 'Generate open-source e-business', '$276.57', '$113.25');
insert into books (author, title, priceOld, price) values ('Lindsay Coutthart', 'Implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author, title, priceOld, price) values ('Helyn Schneidar', 'Utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author, title, priceOld, price) values ('Bette-ann Askem', 'E-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author, title, priceOld, price) values ('Dom Robuchon', 'Facilitate efficient eyeballs', '$232.30', '$131.48');

